name: commit_gitops
on:
  workflow_call:
    inputs:
      app_name:
        required: true
        type: string
      registry_name:
        required: true
        type: string
      tag:
        required: true
        type: string
      values_yaml_path:
        required: true
        type: string
      property_path:
        required: true
        type: string
      target_repo:
        required: false
        type: string
        default: cross-space-official/gitops
    secrets:
      GITOPS_PATOKEN:
        required: true
jobs:
  commit_to_gitops:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.target_repo }}
          token: ${{ secrets.GITOPS_PATOKEN }}
          path: work-dir
      - name: Update staging yaml
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: ${{ inputs.values_yaml_path }}
          propertyPath: ${{ inputs.property_path }}
          value: ${{ inputs.tag }}
          repository: ${{ inputs.target_repo }}
          commitChange: true
          updateFile: true
          createPR: true
          token: ${{ secrets.GITOPS_PATOKEN }}
          branch: release-${{ inputs.app_name }}-${{ inputs.tag }}
          title: Release ${{ inputs.app_name }} ${{ inputs.tag }}
          targetBranch: main
          workDir: work-dir/
          message: 'Commit ${{ inputs.app_name }} with ${{ inputs.tag }}'
          commitUserName: 'mbytesbot'
          commitUserEmail: 'github-bot@meta-bytes.io'
          masterBranchName: main
