name: validate
on:
  workflow_call:
    inputs:
      with_libvips:
        type: boolean
        required: false
        default: false

jobs:
  lint:
    runs-on: ubuntu-latest
    container: golang:1.18.1-bullseye
    steps:
      - name: Prepare Libvips
        if: ${{ inputs.with_libvips == true }}
        run: |
          apt-get update
          apt-get install -y libvips libvips-dev
      - name: Checkout
        uses: actions/checkout@v3
      - name: Prepare Go
        uses: actions/setup-go@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          version: v1.52.0
          args: --timeout=10m
  unit-test:
    needs: lint
    runs-on: ubuntu-latest
    container: golang:1.18.1-bullseye
    steps:
      - name: Prepare Libvips
        if: ${{ inputs.with_libvips == true }}
        run: |
          apt-get update
          apt-get install -y libvips libvips-dev
      - name: Checkout
        uses: actions/checkout@v3
      - run: make ut
